# file to load default parameters.
resolution: 0.05
  
frame_id: 'map'
base_frame_id: 'base_link'

sensor_model/max_range: 2.0

filter_ground: false

color/r: 1.0
color/g: 0.0
color/b: 0.0
color/a: 1.0

latch: false

local_pointcloud_X_length: 4.0
local_pointcloud_Y_length: 4.0
local_pointcloud_Z_length: 4.0

enable_FOV: true
